### ISSUE TITLE
Iterate on email block

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#101]
see feedback here

https://usdrcovid19.slack.com/archives/C010V4G7B98/p1587581346305100?thread_ts=1587483762.237300&cid=C010V4G7B98

**Comment by neelamsaboo** [comment]
@anyapatel27 , @robynashleyPM  Do we need more to be done here? If not, feel free to close this ticket

**Comment by anyapatel27** [comment]
This is along the vein of automating emails via the Volunteer table and thus seems still important, keeping it open.
