### ISSUE TITLE
Server-side rendering for front ent

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keithk** [comment]
@k8reindeer Do we still need this after the work from last week? If so - what are the requirements (what are we trying to solve with SSR)?

**Comment by k8reindeer** [comment]
I don't see why we would need this. It won't solve any problem we have and might make things slower
