### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#109]
We created mailmerge in airtable for Paterson and are almost done with Walnut Creek.
We want to get this documented (geoff prob already has that) and also passed off to someone else on the team to help with.
Ideally I’d also like us to have some kind of simple way for this to be implemented, and guidelines to accounts for what types of emails to promise.
We are in discussion with Sendgrid/twilio to figure out how to get some funds for this – another   to do for product is to figure out sponsorship/funds for sendgrid

**Comment by neelamsaboo** [comment]
No longer relevant
