### ISSUE TITLE
Internal Error after deploying on zeit

### ISSUE THREAD

**Issue by vinit-2997** [usdigitalresponse/neighbor-express#11]
I followed all the instructions and deployed on zeit.
After deployment, there is an Internal server error.

Here is the deployed link : https://neighbor-express-1aoo9y2sz.now.sh/

Errors in console : 
1) Missing languages value in CMS
2)  TypeError: Cannot read property 'split' of undefined

**Comment by keithk** [comment]
@vinit-2997 Sorry! We've made some changes to our base CMS to handle multiple languages, and I think you started before we'd added that.

If you open the `CMS` tab of your airtable, add a new row that has
key: language
data: English:en,Spanish:es

I'm going to add it to our default CMS linked in the github as well, and make sure that we keep that airtable up to date as we push out PRs, and ensure better backwards compatibility. 

I opened #15 to catch for this, and have smart defaults.

**Comment by vinit-2997** [comment]
Great.
Thanks for the update.
