### ISSUE TITLE
Demo Sites

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#110]
Flesh out demo sites / product marketing materials (this I would love to do in coordination with accounts team). We have three sites demo1 / demo2 / demo3

https://demo1.neighborexpress.now.sh/ all are in the airtable

**Comment by neelamsaboo** [comment]
Anya, 
Can you confirm whether this issue is still relevant?

**Comment by anyapatel27** [comment]
We have three sites demo1 / demo2 / demo3.
