### ISSUE TITLE
Finalize documentation organization

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#112]
Airtable –   I hacked this up as a way to keep documentation at least linked to the core   product, for when users get stuck, they could come here to find the   links. https://airtable.com/tbl0nPceXvH9I4cyK/viw93pDlgG9neprmG?blocks=hide The   CMS documentation currently lives here directly. I also have old visual   documentation that I wrote out   here https://whimsical.com/LE8KPDkxRb1gB9GzuX8Qz2 but it’s   outdated. I would like this week to update the CMS documentation in some way   , probably we just add some images to Kate’s already incredible written documentation.
--
I was playing around with using google slides to create   documentation for airtable features, the   blocks. https://docs.google.com/presentation/d/1HEmJHDSBF7yK1JyDiN-7JdwfRPE1-AEqkrAkvHGmzZ0/edit#slide=id.p
Github https://github.com/usdigitalresponse/neighbor-express

**Comment by neelamsaboo** [comment]
@erinfrey ,  Are you working on this item? Lets sync up on documentation and open action items

**Comment by erinfrey** [comment]
Hey @neelamsaboo I just pinged Anya yesterday – yes let's do this after the holiday.
