### ISSUE TITLE
Fix the bus factor

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#113]
Fix the bus factor: Kate is coordinating a time to do an internal training for geoff to explain airtable, robert to explain DNS, ppl to share how things work so we don’t have engineers only owning one thing.

**Comment by neelamsaboo** [comment]
@geoffreylitt  @anyapatel27  Do you know whats this about? Can this be closed?

**Comment by geoffreylitt** [comment]
This was just an idea a while back to have engineers meet and share notes. I think fine to close.

More broadly, would be good to think about knowledge sharing and documentation but I think that's a bigger discussion than this ticket
