### ISSUE TITLE
As a user, if I add a photo block to the CMS, it will be responsive

### ISSUE THREAD

**Issue by erinfrey** [usdigitalresponse/neighbor-express#116]
**Is your feature request related to a problem? Please describe.**
When I add a photo block to the CMS, it isn't responsive.

**Describe the solution you'd like**
I'd like the photo block to be responsive, like the column block is.

**Describe alternatives you've considered**
Currently I can use column to make it responsive–works fine!–but it requires an additional row each time I add a photo. 

**Additional context**
none

**Comment by k8reindeer** [comment]
Hi Erin, can you give more details about what you mean by "responsive", perhaps including screenshots of how it looks with the photo block vs column block on narrow screen widths? I'm not able to reproduce this -- Photo block looks responsive to me
