### ISSUE TITLE
Get NEX CMS running on glitch

### ISSUE THREAD

**Issue by keithk** [usdigitalresponse/neighbor-express#127]
**Is your feature request related to a problem? Please describe.**
This is 100% for my own benefit, but I work on a platform called [Glitch](https://glitch.com). As we consider having the CMS pitched as a more general tool for cities we can make it easier to spin it up to at least take it out for a test drive.

One of the best ✨  best things ✨ about glitch is the ability to "remix" a project. This means that someone (even someone without a glitch account) can go here: https://glitch.com/~neighbor-express and click the **remix** button, and have a fully working NEX CMS in minutes.

**Describe the solution you'd like**
I've created a demo project here: https://glitch.com/~neighbor-express. Any user can click "remix" and after inputting their .env variables (which will not transfer in the case of a remix!) they'll have a functioning CMS immediately.

This gives them a URL (their-name.glitch.me) to immediately see the changes and they can play around with it, giving them a kind of sandbox or playground.

If we agree that this seems like a positive and valuable thing to have, we can craft more concise documentation specifically for the glitch use case, which will require much less "setting up" than getting running on vercel or elsewhere.

**Describe alternatives you've considered**

**Additional context**

**Comment by keithk** [comment]
Interested in what you think @erinfrey and @k8reindeer!

**Comment by k8reindeer** [comment]
Whoa, I tried it out and it works great!
