### ISSUE TITLE
Tests for airtable Send Messages block

### ISSUE THREAD

**Issue by k8reindeer** [usdigitalresponse/neighbor-express#130]
**Is your feature request related to a problem? Please describe.**
There are no tests for the airtable send messages block. It would be good to have automated tests to detect regressions and give us more confidence when deploying.

**Describe the solution you'd like**
Add tests! And then include them in the github test hook so that they run on every change.

**Describe alternatives you've considered**
We could live dangerously... but let's not ;)

**Additional context**
I asked about a recommended test stack on https://community.airtable.com/t/writing-tests-for-custom-blocks/29965, we'll see what they say

**Comment by neelamsaboo** [comment]
@geoffreylitt Is this still open?

**Comment by geoffreylitt** [comment]
Yes, still open.

I don't know the current email sending code super well so I'd need to dig in and learn more before approaching this task

**Comment by neelamsaboo** [comment]
@geoffreylitt   Can we have Lien or Mike pick this up?

**Comment by geoffreylitt** [comment]
Sure that sounds like a good plan. I can assist because I do have a little
context, but makes sense to have one of them pick it up.
