### ISSUE TITLE
Integrate with Galaxy Digital APIs

### ISSUE THREAD

**Issue by neelamsaboo** [usdigitalresponse/neighbor-express#147]
State of Delaware currently has their volunteer data in their own system (Galaxy Digital) and can be extracted using APIs (http://api2.galaxydigital.com/volunteer/docs/).  We discussed two models with their team for integrating with NEX. 
1) Extract the volunteer data using these APIs and upload using CSV to airtable. This model will allow only one-time pull of the volunteer data. 
2) Build a job that will pull the volunteer data using the Galaxy Digital APIs and write to airtable using Airtable APIs. This model will allow continous  sync between these two systems. 

Delaware team is leaning towards the second model, as they plan to use Galaxy Digital for volunteer verification.

**Comment by ghost** [comment]
@neelamsaboo I can take this, can you try to assign to me?

**Comment by ghost** [comment]
@neelamsaboo is this the flow that Delaware would need?

- The ingestion from Galaxy Digital will be an initial load and then we would read results daily (or some other time frequency).  
- neighbor-express is only supplementing an existing volunteer sign up they have and we would not need to post the results back to Galaxy Digital

In addition, could you help me track down the answers to a couple of questions:
- How many new rows do they expect daily/weekly?
- What's the frequency that makes sense?

A couple of thoughts that I have going into this are:
- Ensuring they have full visibility into failures of any sort
     - If the volume is low and the schedule is not as frequent, it may be doable to build a block within airtable to be kicked off manually.  I don't know how plausible this is yet, would have to do some research, but this may give them the best visibility/control into failures to not have to rely on USDR as much in their day-to-day work
- How can we safeguard against API changes (this may not be as big of a concern right now)

**Comment by neelamsaboo** [comment]
@michaelogren You are right about the ingestion flow. We will start with the initial load from Galaxy Digital and then periodically load data from Galaxy Digital to Airtable. We will NOT be posting new data from Air table to Galaxy Digital. It needs to be one-way sync. 
Regarding frequency of sync - We will need to work with the city team. From what I understand, a daily sync will suffice.

**Comment by ghost** [comment]
Galaxy Digital support helped me generate an API key, however I'm unable to see it...womp womp. They seem to be pretty responsive so I replied again asking if I need elevated permission or if I'm flat out missing it

**Comment by ghost** [comment]
The data is synced and we have a script to run complete updates on the volunteer data without issue.  While creating the block, I noticed the the Galaxy Digital API does not set CORS response headers, making the data returned unreadable from the Airtable block.  I'll reach out to their support to see if they can add this for us, but we'll want to consider alternatives as this is probably unlikely to change
