### ISSUE TITLE
Bug: emails aren't sending?

### ISSUE THREAD

**Issue by geoffreylitt** [usdigitalresponse/neighbor-express#150]
Harsha in Paterson says that "emails aren't sending sometimes."

When I ran a test delivery + email in Paterson's real account, I did receive the email successfully. So it does seem like some emails are sending.

Our Sendgrid trial has expired but we're supposed to get 100 emails / day for free, so it's not expected that we would have sending issues.

One possibility I thought of. Currently even if Sendgrid API has an error, we don't surface that in the UI, we swallow the error (iirc). So maybe some of our emails have some bug specific to that template or something.

Some ideas for next steps:

* ask Harsha for more details on what's going on
* try to get better logging and error handling of some kind

**Comment by geoffreylitt** [comment]
I have a lead! A volunteer email recently failed to deliver; the receiving server rejected the email with a DNS error.

<img width="604" alt="Screen Shot 2020-06-30 at 6 35 19 PM" src="https://user-images.githubusercontent.com/934016/86183893-03b86900-bb01-11ea-9bba-0e676f34d964.png">

Our domain is supposed to be configured so that email servers can verify that we're actually the ones sending the emails. We originally set this up in sendgrid a while back but maybe our DNS setup changed and we broke our config?

The next step here is for me to get access to our DNS config and look at what's going on there.

Some notes for reference:

* this history info on individual emails is in the Activity tab of sendgrid
* we only get 3 days of history on our current plan but should get more once we're on a paid plan

**Comment by geoffreylitt** [comment]
Paul at USDR updated our DNS to have the correct entries. Hopefully that fixes this.

I'm going to ask Harsha if we can try re-sending a volunteer email to confirm the fix.

**Comment by geoffreylitt** [comment]
I think we've fixed this. 

Harsha said a volunteer still had trouble receiving an email, but Sendgrid said the email was delivered so I'm not convinced that we actually still have the problem.

**Comment by neelamsaboo** [comment]
Closing it for now. We can open it again, if required
