### ISSUE TITLE
Create the Send Email Messages block in San Ramon's base

### ISSUE THREAD

**Issue by anyapatel27** [usdigitalresponse/neighbor-express#152]
We need to create the Send Email Messages block in their base to be ready for launch (7/6). Robyn and I would love to learn how to do this in order to take this off someone's plate for future launches. Assigning to Geoff for the time being.

**Comment by geoffreylitt** [comment]
@alienngator these are the instructions for how to deploy to a new city:

https://github.com/usdigitalresponse/neighbor-express/tree/master/send_email_messages#setting-up-a-new-city

I've never done it before so I don't know too much more. Do you think you could give it a try?

**Comment by alienngator** [comment]
> @alienngator these are the instructions for how to deploy to a new city:
> 
> https://github.com/usdigitalresponse/neighbor-express/tree/master/send_email_messages#setting-up-a-new-city
> 
> I've never done it before so I don't know too much more. Do you think you could give it a try?

Thanks for the pointer Geoff, super helpful!! Sure -- Neelam asked me to pick up this issue because it's higher priority. I don't know what this involves yet 😅 but will reach out to people if anything isn't clear.

**Comment by geoffreylitt** [comment]
@alienngator sure let me know if you need more help from me. I'm also happy to take this one over from you at any point if you prefer.

Basically we have an email system built using the [Airtable Blocks SDK](https://airtable.com/developers/blocks). The goal of this task is to deploy that system to the Airtable base for San Ramon.

The instructions I linked to above should walk through it, should be just a few CLI commands.

**Comment by alienngator** [comment]
![Screenshot from 2020-07-22 01-26-22](https://user-images.githubusercontent.com/5952625/88153604-7aa1c880-cbba-11ea-99de-4cad6d8a2d5a.png)
Done, closing issue.
