### ISSUE TITLE
Project lacks license or reuse guidance

### ISSUE THREAD

**Issue by jadudm** [usdigitalresponse/neighbor-express#172]
**Describe the bug**

The project seems to lack a license? (Is it FOSS? Can it be reused by others? Under what conditions?)

It would be good to know under what terms the work can, or can not, be built upon and/or replicated. Apologies if it is documented in the repo somewhere, but it seems to neither be in its own file or in the README.

No other open issues seem to deal with a license, based on a search for the word "license"

**To Reproduce**

Look in the repository for a LICENSE.md, or some mention of license in the README.

**Expected behavior**

A license of some sort.

**Screenshots**

See repository.

**Additional context**

This project is featured here:

https://newamericafoundation.github.io/pandemic-response-repository/projects/neighbor-express/

but it is difficult to tell if it is actually a FOSS project, or could be safely replicated, because of the license.

**Comment by geoffreylitt** [comment]
The project is MIT licensed. There's a LICENSE file: https://github.com/usdigitalresponse/neighbor-express/blob/master/LICENSE

But it's a good point that it should be mentioned in the README, I'll go ahead and do that.

**Comment by jadudm** [comment]
Apologies; I should have seen that.

I've submitted a PR against 

https://github.com/newamericafoundation/pandemic-response-repository/compare/master...jadudm:patch-1

to update their data re: this project. Many thanks!
