### ISSUE TITLE
Loading indicator / time to first paint

### ISSUE THREAD

**Issue by keithk** [usdigitalresponse/neighbor-express#29]
**Describe the bug**
Because we're fetching our entire CMS data on page load (and not just content), we don't have anything to display to the users for a few moments.

I can think of a few ways to approach this:
- Have a cached version of the CMS built _on deploy_ by the deploy script, that saves to something like `cached.json` - that is what is displayed to the user until we pull from the CMS (more work)
- Showing a loading indicator, using something like: https://klendi.github.io/react-top-loading-bar/ (less work)

I'd advocate for #2 just as it requires less work, and we can use the same visual indicator when navigating between pages

**Comment by k8reindeer** [comment]
I love the idea of #1, but agree let's do #2 first, it's useful regardless!
