### ISSUE TITLE
Onboarding Template

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#42]
Volunteer Sign-up Form: https://airtable.com/shrHLMkLcF5d5ZvZf?prefill_How%20did%20you%20hear%20about%20us%3F=usdigitalresponse.org

Oath Signing Form: https://docs.google.com/forms/d/e/1FAIpQLSfeFiTsgd-RHifCsaxtT4yJcv5uGavxC3D30EwNOf-dqVaQJg/viewform?fbzx=3843283700635169826
Give them permission to add their information to this contact directory: https://airtable.com/tbl4KFCOnnKaASxjn/viwV89r93QXpnMnVQ?blocks=hide
Invite them to this Trello board

Give them access and link them to Neighbor Express Google Drive: https://drive.google.com/drive/folders/1wTQ0wyVu0HJWnT6JzTVAh62Ep3U0T05s
Invite them to Slack
Invite them to Daily Standup

Send them/give them access to onboarding document once they have permissions to the above: https://docs.google.com/document/d/1ZLQKxIyPhJw50lREJO_bLSeJhcIxDTTfewLf_P-Yms0/edit

**Comment by neelamsaboo** [comment]
@anyapatel27  @robynashleyPM   Is this work in progress or done?
