### ISSUE TITLE
Text - SMS functionality 

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#62]

**Comment by neelamsaboo** [comment]
Automating SMS'ing for all deliveries.

**Comment by neelamsaboo** [comment]
Automating SMS'ing for all deliveries and processes.

**Comment by moniquebaenatan** [comment]
As part of the UX research study completed in the Spring/Summer 2020, texting functionality was brought up by various groups. A brainstorm of functionality, requirements, blockers and user groups was conducted in August 2020 and can be found [here](https://docs.google.com/document/d/1SvMopDpueIQylhXo3ntIn-xUPKtUiiCxl3jcYhxC0F8/edit?ts=5f275e52)

To get Neighbor Express set up with a Twilio grant for Covid relief, apply [here](https://www.twilio.org/application/)

Luis Liang <lliang@twilio.com> is point of contact at Twilio.org
