### ISSUE TITLE
Automating auto email or text replies immediately after form submittal

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chompasina** [comment]
I know you all were working on a nice scripting block to track sent emails which could be combined with this, but for our purposes, I created a simple Zap for auto-response emails which was really easy to set up for Milwaukee's NEx instance. 
Things learned: For tracking purposes, we just BCC'd the organization's email address. To avoid accidental or repeat sends, use the 'locked view' feature to prevent changes to the view's filters from triggering the zap.
