### ISSUE TITLE
Move Google Maps API from Geoffrey's personal acct to shared acct

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#88]

**Comment by neelamsaboo** [comment]
@geoffreylitt  Is this still open?

**Comment by geoffreylitt** [comment]
Yes, still open. Doesn't feel super urgent personally (our usage is low enough that I'm not really getting billed any money) but maybe for account hygeine purposes we want to move to a USDR account.

@neelamsaboo Do you know who to ask at USDR about moving accounts over? I guess Paul maybe?
