### ISSUE TITLE
Customizable city-specific logo in header

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#89]
https://usdrcovid19.slack.com/archives/C010GA1ES4Q/p1587752128414500?thread_ts=1587751051.413800&cid=C010GA1ES4Q

Related to this, one of my smaller UX design thoughts was to have a dedicated space in the header within the template for cities to place their seals (and any partner logos). Helps brand the site to users as official, increasing their level of trust. Probably a larger dev change, but thought I'd mention it in this thread.

**Comment by k8reindeer** [comment]
I attempted to tackle this and ran into USWDS limitations, mentioned here: https://usdrcovid19.slack.com/archives/C010V4G7B98/p1588634597064000

specifically https://github.com/uswds/uswds/issues/1769 and https://github.com/uswds/uswds/issues/1594
